### PR TITLE
Fix login

### PR DESCRIPTION
**Pull request by skrzepto**
Modifying sqlalchmey naive datetime to utcdatetime so that login will work

 Issue #195

### CODE REVIEW

**Comment by skrzepto** [comment]
This will also allow my testsuite to pass

**Comment by laxathom** [comment]
Hey, well you don't need actually to abstract the datetime to handle utc there.
DateTime handles it already with param timezone :wink: 
That's the fix I have locally on @pypingou 's branch. I think we can close that PR

**Comment by laxathom** [comment]
That's b/c you have a previous stored naive-offset datetime. Did you rebuild the db from scratch?
Also, I did remove the non-sense default value on `login_timestamp` as when the user get created, it actually never logged in yet.

**Comment by skrzepto** [comment]
@laxathom updated this PR to reflect your comments. It works on my machine

**Comment by skrzepto** [comment]
Okay there are two methods I got the original implementation from 

http://stackoverflow.com/questions/2528189/can-sqlalchemy-datetime-objects-only-be-naive/2528453#2528453


But there seems to be a lib for this as well

https://pypi.python.org/pypi/SQLAlchemy-UTCDateTime/

which way should we go?

**Pull request closed without merging**
