### PR TITLE
Fix two separate fatals

### PR DESCRIPTION
**Pull request by relrod**

### CODE REVIEW

**Comment by laxathom** [comment]
ya, ya, :+1: on catching such error.
though we have email delivery in few places which would need to be extracted and put at one place with a listener avoiding to fix this everywhere.
I'm re-thinking the whole notification system to handler more than one backend (email, fedmsg, etc).
Will add that changes in fas/subscribers in the mean time.

**Comment by pypingou** [comment]
@laxathom so should this be merged or close?

**Comment by laxathom** [comment]
Closed.

**Comment by relrod** [comment]
@laxathom Should we at least cherry-pick 6e8939ec8a9fa1e34d32414bce74e1f825098695 from this?

**Comment by laxathom** [comment]
Sure thing.

**Pull request closed without merging**
