### PR TITLE
Allow the registration form to work again...

### PR DESCRIPTION
**Pull request by relrod**
Not sure if these are the best fixes. In particular, I don't know how the license form is supposed to work, but right now I don't see any such form when I sign up, so I assume that is still WIP.

### CODE REVIEW

**Comment by laxathom** [comment]
You have to enable the license at sign-up (when adding one) to make live at sign up process.
Is this what you did and still got nothing?

**Comment by relrod** [comment]
@laxathom I didn't add one before, but I just tried it and if I add one and check the box for required at sign-up, and then I create a new account, I still get a runtime error:

```
Traceback (most recent call last):
  File "/home/ricky/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_debugtoolbar-2.3-py2.7.egg/pyramid_debugtoolbar/toolbar.py", line 178, in toolbar_tween
    response = _handler(request)
  File "/home/ricky/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_debugtoolbar-2.3-py2.7.egg/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/ricky/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/ricky/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_tm-0.10-py2.7.egg/pyramid_tm/__init__.py", line 95, in tm_tween
    reraise(*exc_info)
  File "/home/ricky/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid_tm-0.10-py2.7.egg/pyramid_tm/__init__.py", line 76, in tm_tween
    response = handler(request)
  File "/home/ricky/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/ricky/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/ricky/.virtualenvs/fas-python2.7/lib/python2.7/site-packages/pyramid-1.5.2-py2.7.egg/pyramid/config/views.py", line 477, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/ricky/devel/python/fedora/fas/fas/views/register.py", line 94, in account
    la_form.license.data = la.id
AttributeError: 'NoneType' object has no attribute 'license'
```

**Comment by pypingou** [comment]
@laxathom ?

**Comment by pypingou** [comment]
@laxathom ?

**Comment by laxathom** [comment]
Added locally.

**Pull request closed without merging**
