### PR TITLE
Allow accessing group profile by their name instead of id

### PR DESCRIPTION
**Pull request by pypingou**
And first check if there is a group, then retrieve its members, otherwise
we end up with no group found, not because it doesn't exist but because
there are no members anymore.

### CODE REVIEW

**Comment by pypingou** [comment]
This relates to https://github.com/fedora-infra/fas/issues/186

Basically here we're using the group name instead of its display name

**Comment by laxathom** [comment]
:+1:  from me

**Comment by pypingou** [comment]
Adjusted :)

**Comment by laxathom** [comment]
:+1: with update

**Comment by pypingou** [comment]
Thanks

**Pull request merged**
