### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by puiterwijk**
Two small fixes

### CODE REVIEW

**Comment by laxathom** [comment]
:+1:  from me.

**Comment by laxathom** [comment]
Oh, one thing. You shoudl request your PR against develop branch which is the main one not master.

**Comment by puiterwijk** [comment]
I know that develop is the development branch, but the fixes that I am currently bringing in are emergency fixes, and master was the version deployed into production :-).
So after the infra freeze is lifted, we can merge everything from devel into master and make a new release.

**Comment by laxathom** [comment]
wfm

**Pull request merged**
