### PR TITLE
Remove reference to fedorahosted

### PR DESCRIPTION
**Pull request by axk4545**

### CODE REVIEW

**Comment by axk4545** [comment]
@pypingou @puiterwijk is this ready to merge?

**Comment by pypingou** [comment]
I'm curious why there are so many merge commits in there

**Comment by axk4545** [comment]
if they are from me I can squash @pypingou

**Comment by pypingou** [comment]
@axk4545 look at the commit list of this PR https://github.com/fedora-infra/fas/pull/265/commits there are 6 commits while only one is from you

**Comment by axk4545** [comment]
Which I did not fully realize when I made that comment...

On Feb 22, 2018 10:07 AM, "Pierre-Yves Chibon" <notifications@github.com>
wrote:

@axk4545 <https://github.com/axk4545> look at the commit list of this PR
https://github.com/fedora-infra/fas/pull/265/commits there are 6 commits
while only one is from you

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fedora-infra/fas/pull/265#issuecomment-367709682>, or mute
the thread

**Comment by laxathom** [comment]
Closing as changes already included  from 04e6084ffc31051674f53bde71dc4a9336823812

**Pull request closed without merging**
