### PR TITLE
Issue #173: if the irc nick field is empty set it to None instead

### PR DESCRIPTION
**Pull request by skrzepto**
#173 
If the irc nick field is empty set it to None instead

### CODE REVIEW

**Comment by pypingou** [comment]
:+1: for me

**Comment by pypingou** [comment]
We may want to ``.strip()`` while at it, unless it's already done somewhere (and that might be true for more fields)

**Comment by skrzepto** [comment]
Forgot about that edge case, let me test locally to see if it faults.

**Comment by pypingou** [comment]
> let me test locally

Unit-tests!! Ok I'm out :D

**Comment by skrzepto** [comment]
> >let me test locally

> Unit-tests!! Ok I'm out :D

Soon :) still trying to fully understand how fas works

**Comment by skrzepto** [comment]
Looks like the other unique fields have some kind of client verification. I'll look into writing unittests now to this

**Comment by laxathom** [comment]
Have you looked at defined a default `None` here https://github.com/fedora-infra/fas/blob/FAS_3.0/fas/forms/people.py#L166 see if this work? This might avoid to add am if statement on the register.

**Comment by skrzepto** [comment]
@laxathom  unfortunately the default `None` doesn't help at least doesn't pass the unit tests I wrote. But this change does

**Comment by skrzepto** [comment]
Any comments on this?

**Comment by skrzepto** [comment]
@bowlofeggs I applied you feedback, thanks :) are we good to merge?

**Pull request merged**
