### PR TITLE
Only the message of an exception is JSON encodable

### PR DESCRIPTION
**Pull request by relrod**
Fixes another set of runtime errors…

### CODE REVIEW

**Comment by ralphbean** [comment]
I'll leave this one for @laxathom to look at.

Maybe other details of the error could be returned?  The traceback is perhaps encodable?  Should we return other context?

**Comment by relrod** [comment]
Well as it stands it throws runtime errors instead of JSON ;)

**Comment by laxathom** [comment]
Correct! pypingou meant to return it as json output.
Ok, As I'm currently implementing the private API, I'm factoring a bit the API to handler both public and private requests, so if you see issue, I propose we sync up, does that work for you?

**Comment by relrod** [comment]
@laxathom Ok - are you fixing this issue in your refactor? Should I close this issue?

**Comment by laxathom** [comment]
Yep, you can close. 
Thanks for pointing this out.

**Pull request closed without merging**
