### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.fedoraproject.org/projects/fedora-infra/fas/) for fedora-infra/fas.

### CODE REVIEW

**Comment by Jibec** [comment]
this refers to: https://github.com/fedora-infra/fas/issues/142

**Comment by Jibec** [comment]
well, did someone unlocked the repository?

**Comment by rffontenelle** [comment]
Interesting how the contribution is closed, but it allows start a language (i.e. creating the translation file).

**Comment by ryanlerch** [comment]
Closing this Pull Request as the FAS project is now archived, not actively developed, and unmaintained.

FAS was replaced in March 2021 by Fedora Accounts (https://accounts.fedoraproject.org).

If this PR is a Feature Addition that might be beneficial to Fedora Accounts, consider reworking and refiling it against [Noggin](https://github.com/fedora-infra/noggin)

**Comment by Jibec** [comment]
FYI, I made sure language addition is not possible anymore and removed 
the empty languages to prevent Weblate opening a new PR.

**Pull request closed without merging**
